version: '3.8'
services:
  nextjs-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
      - .env.local
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro